(defun install-eaf-dependencies ()
  (interactive)
  (let ((default-directory "/sudo::")
        (eaf-dir (file-name-directory (locate-library "eaf"))))
    (shell-command (concat eaf-dir "install-eaf.sh" "&"))))

(defun duckduckgo ()
  (interactive)
  (eaf-open-browser "www.duckduckgo.com"))
(defun wikipedia ()
  (interactive)
  (eaf-open-browser "www.wikipedia.com"))
(defun youtube ()
  (interactive)
  (eaf-open-browser "www.youtube.com"))
